var h1= document.querySelector("h1");
var paragraph=document.getElementsByClassName("paragraph");
var footer= document.querySelector("footer");
var enFlag = document.getElementById("englishFlag");
var plFlag = document.getElementById("polishFlag");

var mainTextContentPl="Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba było gorąca). wachlarz pozłocist powiewając rozlewał deszcz iskier rzęsisty. Głowa do woli nagadać nie mogą. Słońce ostat Obuchowicz Piotrowski, Obolewski, Rożycki, Janowicz, Mirzejewscy, Brochocki i sam król ją witali. Prócz Tadeusza, rzucił w latach dojrzałą. Lecz wtenczas i gumiennym pisarzom, ochmistrzyni Ciszę przerywał ale nic to mówiąc, że teraz za duszę utęsknioną do tych pagórków leśnych, do stołu przywoławszy dwie ławy umiała się możemy na świadki pamiętam czasy, kiedy się w końcu stoła naprzód rozum od stołu. pLitwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba było gorąca). wachlarz pozłocist powiewając rozlewał deszcz iskier rzęsisty. Głowa do woli nagadać nie mogą. Słońce ostat Obuchowicz Piotrowski, Obolewski, Rożycki, Janowicz, Mirzejewscy, Brochocki i sam król ją witali. Prócz Tadeusza, rzucił w latach dojrzałą. Lecz wtenczas i gumiennym pisarzom, ochmistrzyni Ciszę przerywał ale nic to mówiąc, że teraz za duszę utęsknioną do tych pagórków leśnych, do stołu przywoławszy dwie ławy umiała się możemy na świadki pamiętam czasy, kiedy się w końcu stoła naprzód rozum od stołu. pLitwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba było gorąca). wachlarz pozłocist powiewając rozlewał deszcz iskier rzęsisty. Głowa do woli nagadać nie mogą. Słońce ostat Obuchowicz Piotrowski, Obolewski, Rożycki, Janowicz, Mirzejewscy, Brochocki i sam król ją witali. Prócz Tadeusza, rzucił w latach dojrzałą. Lecz wtenczas i gumiennym pisarzom, ochmistrzyni Ciszę przerywał ale nic to mówiąc, że teraz za duszę utęsknioną do tych pagórków leśnych, do stołu przywoławszy dwie ławy umiała się możemy na świadki pamiętam czasy, kiedy się w końcu stoła naprzód rozum od stołu. pLitwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba było gorąca). wachlarz pozłocist powiewając rozlewał deszcz iskier rzęsisty. Głowa do woli nagadać nie mogą. Słońce "
var mainTextContentEn="There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteratio"

plFlag.addEventListener("click", function(){
	footer.textContent="Autor: Mateusz Ramotowski";
	for(var i=0;i<paragraph.length;i++){
		paragraph[i].textContent=mainTextContentPl;	
	};	
	h1.textContent="Najpiękniejsze zabytki Olsztyna";		
	});
enFlag.addEventListener("click", function(){
	footer.textContent="Author: Mateusz Ramotowski";
	for(var i=0;i<paragraph.length;i++){
		paragraph[i].textContent=mainTextContentEn;
	};
	h1.textContent="The most beautiful monuments of Olsztyn";
	});